#!/usr/bin/env python3
"""Build human review queue from soften-map + classic-all meta.

High-confidence first: lost edge words, euphemism pairs, high hardness gain.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from phrase_diff import format_unified_diff_block  # noqa: E402


def main() -> None:
    soften = json.loads((ROOT / "reports" / "soften-map.json").read_text(encoding="utf-8"))
    meta_path = ROOT / "packs" / "library" / "01-classic-all.meta.json"
    meta = (
        json.loads(meta_path.read_text(encoding="utf-8"))
        if meta_path.exists()
        else {"entries": []}
    )

    lines = [
        "# Review queue — high-confidence softens",
        "",
        "Human checklist before cutting a curated release pack.",
        "Auto-generated by `scripts/build_review_queue.py`.",
        "",
        "Legend: `[ ]` unreviewed · check boxes offline or via PR notes.",
        "",
        "---",
        "",
        "## A. Pack restores with positive hardness gain",
        "",
        "_From `01-classic-all` meta (strict harder than target)._",
        "",
    ]

    entries = sorted(meta.get("entries") or [], key=lambda e: -e.get("gain", 0))
    for i, e in enumerate(entries[:50], 1):
        lines.append(
            f"### {i}. `{e['key']}`  (+{e.get('gain', 0)} hard)  ← `{e.get('chosen_version')}`"
        )
        lines.append("")
        lines.append(f"- [ ] Reviewed")
        lines.append(f"- Pick: `{e.get('pick_reason', '')}`")
        lines.append(f"- Edge: {e.get('edge_chosen')} → target {e.get('edge_target')}")
        if e.get("diff_summary"):
            lines.append(f"- Diff summary: `{e['diff_summary']}`")
        hunks = e.get("diff_hunks") or []
        if hunks:
            lines.append("")
            lines.append("```diff")
            lines.append(f"# chosen → target")
            for h in hunks[:8]:
                op = h.get("op")
                if op in ("delete", "replace") and h.get("old"):
                    lines.append(f"- {h['old']}")
                if op in ("insert", "replace") and h.get("new"):
                    lines.append(f"+ {h['new']}")
            lines.append("```")
        lines.append("")

    lines += [
        "---",
        "",
        "## B. Soften-map events (edge lost or euphemism)",
        "",
    ]
    events = soften.get("events") or []
    scored = [
        ev
        for ev in events
        if ev.get("edge_lost")
        or any("→" in h or "\u2192" in h for h in (ev.get("euphemism_hits") or []))
    ]
    scored.sort(key=lambda e: -e.get("score", 0))
    for i, ev in enumerate(scored[:40], 1):
        lines.append(
            f"### B{i}. `{ev['key']}`  {ev['from_version']} → {ev['to_version']}  "
            f"(score {ev.get('score')}, sim {ev.get('similarity', 0):.0%})"
        )
        lines.append("")
        lines.append(f"- [ ] Reviewed")
        if ev.get("edge_lost"):
            lines.append(f"- Edge lost: {', '.join(ev['edge_lost'])}")
        if ev.get("euphemism_hits"):
            lines.append(f"- Euphemism: {', '.join(ev['euphemism_hits'])}")
        if ev.get("diff_summary"):
            lines.append(f"- Diff: `{ev['diff_summary']}`")
        hunks = ev.get("diff_hunks") or []
        if hunks:
            lines.append("")
            lines.append("```diff")
            for h in hunks[:6]:
                op = h.get("op")
                if op in ("delete", "replace") and h.get("old"):
                    lines.append(f"- {h['old']}")
                if op in ("insert", "replace") and h.get("new"):
                    lines.append(f"+ {h['new']}")
            lines.append("```")
        lines.append("")

    out = ROOT / "reports" / "review-queue.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(entries)} pack entries, {len(scored)} soften events with edge/eu)")


if __name__ == "__main__":
    main()
